-- P1 功能：Intake 流程、消失偵測召回、情感式付費牆所需欄位
ALTER TABLE users ADD COLUMN join_date TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN onboarding_step INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN onboarding_q1 TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN onboarding_q2 TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN nickname TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN last_active TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN silence_stage INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN paywall_triggered INTEGER NOT NULL DEFAULT 0;
